//
//  NSColor+Extensions.h
//  iOSCoreLibrary
//
//  Created by Iain McManus on 12/06/2015.
//  Copyright (c) 2015 Iain McManus. All rights reserved.
//

#if TARGET_OS_IPHONE

#else

#import <Cocoa/Cocoa.h>

@interface NSColor (Extensions)

- (NSString*) hexString;

- (NSString*) htmlHexString;

+ (NSColor*) fromHexString:(NSString*) inHexString;

- (CGFloat) perceivedBrightness;

- (NSColor*) autoGenerateDifferentShade;

- (NSColor*) autoGenerateLighterShade;

- (NSColor*) autoGenerateMuchLighterShade;

@end

#endif // !TARGET_OS_IPHONE