//
//  UIColor+extensions.h
//  iOSCoreLibrary
//
//  Created by Iain McManus on 1/07/13.
//
//

#import <UIKit/UIKit.h>

@interface UIColor (extensions)

- (NSString*) hexString;

+ (UIColor*) fromHexString:(NSString*) inHexString;

- (CGFloat) perceivedBrightness;

- (UIColor*) AutoGenerateDifferentShade;

- (UIColor*) AutoGenerateLighterShade;

- (UIColor*) AutoGenerateMuchLighterShade;

@end
