//
//  UIColor+extensions.h
//  iOSCoreLibrary
//
//  Created by Iain McManus on 1/07/13.
//
//

#if TARGET_OS_IPHONE

#import <UIKit/UIKit.h>

@interface UIColor (extensions)

- (NSString*) hexString;

- (NSString*) htmlHexString;

+ (UIColor*) fromHexString:(NSString*) inHexString;

- (CGFloat) perceivedBrightness;

- (UIColor*) autoGenerateDifferentShade;

- (UIColor*) autoGenerateLighterShade;

- (UIColor*) autoGenerateMuchLighterShade;

@end

#endif // TARGET_OS_IPHONE